# Generated by Django 4.2.1 on 2023-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Your unique rest id')),
                ('open_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('city_group', models.CharField(choices=[('B', 'Big city'), ('O', 'Other')], max_length=1)),
                ('type', models.CharField(choices=[('FC', 'FC'), ('IL', 'IL'), ('DT', 'DT'), ('MB', 'MB')], max_length=2)),
                ('P1', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P2', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P3', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P4', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P5', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P6', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P7', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P8', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P9', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P10', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P11', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P12', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P13', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P14', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P15', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P16', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P17', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P18', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P19', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P20', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P21', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P22', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P23', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P24', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P25', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P26', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P27', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P28', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P29', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P30', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P31', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P32', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P33', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P34', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P35', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P36', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('P37', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('revenue', models.DecimalField(decimal_places=1, max_digits=15)),
            ],
        ),
    ]
