# Generated by Django 4.2.1 on 2023-05-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdata',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=15, null=True),
        ),
    ]
