# Generated by Django 4.2.1 on 2023-05-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_revenue', '0004_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNParameter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Your unique rest id')),
                ('P1', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('P2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P4', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P5', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P6', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P7', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P8', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P9', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P10', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P11', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P12', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P13', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P14', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P15', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P16', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P17', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P19', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P20', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P21', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P22', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P23', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P24', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P25', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P26', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P27', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P28', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P29', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P30', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P31', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P32', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P33', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P34', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P35', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P36', models.DecimalField(decimal_places=1, max_digits=3)),
                ('P37', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantdata',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurantdata',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='./web_app_files'),
        ),
        migrations.AddField(
            model_name='restaurantdata',
            name='pnparameter_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_revenue.pnparameter'),
            preserve_default=False,
        ),
    ]
